version: '3.8'

services:
  post_service:
    container_name: post_service
    build:  ./post_service
    depends_on:
      - "postgresdb"
    ports:
      - "9000:9000"
    
  service:
    container_name: service
    build:   ./service
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  
  api:
    container_name: api
    build: ./Api
    ports:
      - "8080:8080"
  
  postgresdb:
    container_name: postgresdb
    image: postgres:14.1
    environment:
      POSTGRES_DATABASE: userss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    expose:
      - "5432"
    ports: 
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p 5432
  
  redisdb:
    container_name: redisdb
    image:  redis
    expose:
      - "6378"
    ports:
      - "6378:6378"


volumes:
  dbdata:



