version: '3.8'

services:
  post_service:
    container_name: post_service
    build:  ./post_service
    depends_on:
      - "postgresdb"
      - "redisdb"
      # - "migrate"
    ports:
      - "8000:8000"
    
  service:
    container_name: service
    build:   ./service
    depends_on:
      - "postgresdb"
    ports:
      - "9000:9000"
  
  api:
    container_name: api
    build: ./Api
    ports:
      - "8080:8080"
  
  postgresdb:
    container_name: postgresdb
    image: postgres:14.1
    # networks:
    #         new:
    #             aliases:
    #                 - database
    environment:
      POSTGRES_DATABASE: userss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    expose:
      - "5433"
    ports: 
      - "5433:5433"
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p 5433

  # migrate:
  #     image: migrate/migrate
  #     networks:
  #       - new
  #     volumes:
  #       - ./migrations:/migrations
  #     command: ["-path", "/migrations", "-database",  "postgres://postgres:1@postgresdb:5433/userss?sslmode=disable", "up",]
  #     links: 
  #       - postgresdb

  redisdb:
    container_name: redisdb
    image:  redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

# networks:
#   new:
volumes:
  dbdata:



